name: Java Assignment CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test-package:
    name: Build, test & package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Build, test and package (java-assignment)
        working-directory: ./java-assignment
        run: |
          chmod +x ./mvnw
          ./mvnw -B clean package -DskipTests=false

      - name: Upload JAR (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: quarkus-app
          path: java-assignment/target/quarkus-app/
          if-no-files-found: warn

